
   --------------------------------------------------------
--  Fichier créé - jeudi-novembre-04-2021
--------------------------------------------------------
DROP TABLE "YOMNA"."LOGMENT" cascade constraints;
DROP TABLE "YOMNA"."MAINTENIR" cascade constraints;
DROP TABLE "YOMNA"."PARTICIPANT" cascade constraints;
DROP TABLE "YOMNA"."PERSONNEL" cascade constraints;
DROP TABLE "YOMNA"."SPECTATEUR" cascade constraints;
DROP TABLE "YOMNA"."SPORT" cascade constraints;
DROP TABLE "YOMNA"."TERRAIN" cascade constraints;
--------------------------------------------------------
--  DDL for Table LOGMENT
--------------------------------------------------------

  CREATE TABLE "YOMNA"."LOGMENT"
   (	"NOM_LOG" VARCHAR2(20 BYTE),
	"NBR_ETOILE" NUMBER,
	"ADRESSE_L" VARCHAR2(20 BYTE),
	"NBR_CH" NUMBER,
	"DISPONIBILITE" VARCHAR2(20 BYTE),
	"TYPE_L" VARCHAR2(20 BYTE),
	"IN_OUT" VARCHAR2(20 BYTE),
	"ID_PAR" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MAINTENIR
--------------------------------------------------------

  CREATE TABLE "YOMNA"."MAINTENIR"
   (	"CIN" NUMBER,
	"IDTERRAIN" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PARTICIPANT
--------------------------------------------------------

  CREATE TABLE "YOMNA"."PARTICIPANT"
   (	"ID" NUMBER,
	"NOM" VARCHAR2(20 BYTE),
	"PRENOM" VARCHAR2(20 BYTE),
	"EQUIPE" VARCHAR2(20 BYTE),
	"ETAT" VARCHAR2(20 BYTE),
	"TYPE" VARCHAR2(20 BYTE),
	"NATIONALITE" VARCHAR2(20 BYTE),
	"DATE_NAIS" DATE,
	"MEDAILLE" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERSONNEL
--------------------------------------------------------

  CREATE TABLE "YOMNA"."PERSONNEL"
   (	"NOM_P" VARCHAR2(20 BYTE),
	"PRENOM_P" VARCHAR2(20 BYTE),
	"CIN_P" NUMBER,
	"GRADE_P" VARCHAR2(20 BYTE),
	"DATE_N_P" DATE,
	"NUM_TEL_P" NUMBER,
	"ADRESS_P" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SPECTATEUR
--------------------------------------------------------

  CREATE TABLE "YOMNA"."SPECTATEUR"
   (	"CIN" NUMBER,
	"NOM" VARCHAR2(20 BYTE),
	"AGE" NUMBER,
	"NUM_SIEGE" NUMBER,
	"ID_TER" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SPORT
--------------------------------------------------------

  CREATE TABLE "YOMNA"."SPORT"
   (	"ID" NUMBER,
	"NOM" VARCHAR2(20 BYTE),
	"TYPE" VARCHAR2(20 BYTE),
	"NBR_PARTICIPANT" VARCHAR2(20 BYTE),
	"DUREE_MATCH" NUMBER,
	"ID_PA" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TERRAIN
--------------------------------------------------------

  CREATE TABLE "YOMNA"."TERRAIN"
   (	"ID" NUMBER,
	"NOM_T" VARCHAR2(20 BYTE),
	"TYPE_T" VARCHAR2(20 BYTE),
	"ETAT_T" VARCHAR2(20 BYTE),
	"CAPACITE" VARCHAR2(20 BYTE),
	"ID_PAR" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into YOMNA.LOGMENT
SET DEFINE OFF;
REM INSERTING into YOMNA.MAINTENIR
SET DEFINE OFF;
REM INSERTING into YOMNA.PARTICIPANT
SET DEFINE OFF;
Insert into YOMNA.PARTICIPANT (ID,NOM,PRENOM,EQUIPE,ETAT,TYPE,NATIONALITE,DATE_NAIS,MEDAILLE) values ('264185','nouira','YOMNA','brazil','bless??','foot','suisse',to_date('31/10/21','DD/MM/RR'),'16');
Insert into YOMNA.PARTICIPANT (ID,NOM,PRENOM,EQUIPE,ETAT,TYPE,NATIONALITE,DATE_NAIS,MEDAILLE) values ('0','YOMNA','samir','brazil','bless??','foot','aqsd',null,'3');
Insert into YOMNA.PARTICIPANT (ID,NOM,PRENOM,EQUIPE,ETAT,TYPE,NATIONALITE,DATE_NAIS,MEDAILLE) values ('5624','ddfsqd','fdqsqfds','brazil','bless??','foot','dsff',null,'20');
Insert into YOMNA.PARTICIPANT (ID,NOM,PRENOM,EQUIPE,ETAT,TYPE,NATIONALITE,DATE_NAIS,MEDAILLE) values ('2356','nouira','YOMNA','brazil','bless??','foot','germany',to_date('01/01/00','DD/MM/RR'),'13');
Insert into YOMNA.PARTICIPANT (ID,NOM,PRENOM,EQUIPE,ETAT,TYPE,NATIONALITE,DATE_NAIS,MEDAILLE) values ('5065','nouira','YOMNA','brazil','bless??','foot','tunisian',to_date('30/11/05','DD/MM/RR'),'30');
Insert into YOMNA.PARTICIPANT (ID,NOM,PRENOM,EQUIPE,ETAT,TYPE,NATIONALITE,DATE_NAIS,MEDAILLE) values ('31562','nouira','YOMNA','brazil','bless??','foot','tunisia',to_date('01/01/00','DD/MM/RR'),'999946');
Insert into YOMNA.PARTICIPANT (ID,NOM,PRENOM,EQUIPE,ETAT,TYPE,NATIONALITE,DATE_NAIS,MEDAILLE) values ('859452','tekaya','syrine','germany','Bonne','basket','tunisia',to_date('13/01/01','DD/MM/RR'),'3');
Insert into YOMNA.PARTICIPANT (ID,NOM,PRENOM,EQUIPE,ETAT,TYPE,NATIONALITE,DATE_NAIS,MEDAILLE) values ('55456','nouira','dzqsd','brazil','bless??','foot','sdqs',to_date('01/01/00','DD/MM/RR'),'62323');
Insert into YOMNA.PARTICIPANT (ID,NOM,PRENOM,EQUIPE,ETAT,TYPE,NATIONALITE,DATE_NAIS,MEDAILLE) values ('2315','dsqf','nouira','brazil','bless??','foot','tunisie',to_date('01/01/00','DD/MM/RR'),'0');
Insert into YOMNA.PARTICIPANT (ID,NOM,PRENOM,EQUIPE,ETAT,TYPE,NATIONALITE,DATE_NAIS,MEDAILLE) values ('564548','layouni','yomna','germany','Bonne','basket','germany',to_date('28/09/01','DD/MM/RR'),'1');
REM INSERTING into YOMNA.PERSONNEL
SET DEFINE OFF;
REM INSERTING into YOMNA.SPECTATEUR
SET DEFINE OFF;
REM INSERTING into YOMNA.SPORT
SET DEFINE OFF;
REM INSERTING into YOMNA.TERRAIN
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index LOGMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YOMNA"."LOGMENT_PK" ON "YOMNA"."LOGMENT" ("NOM_LOG")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PARTICIPANT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YOMNA"."PARTICIPANT_PK" ON "YOMNA"."PARTICIPANT" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PERSONNEL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YOMNA"."PERSONNEL_PK" ON "YOMNA"."PERSONNEL" ("CIN_P")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SPECTATEUR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YOMNA"."SPECTATEUR_PK" ON "YOMNA"."SPECTATEUR" ("CIN")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SPORT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YOMNA"."SPORT_PK" ON "YOMNA"."SPORT" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TERRAIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YOMNA"."TERRAIN_PK" ON "YOMNA"."TERRAIN" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table LOGMENT
--------------------------------------------------------

  ALTER TABLE "YOMNA"."LOGMENT" MODIFY ("ID_PAR" NOT NULL ENABLE);
  ALTER TABLE "YOMNA"."LOGMENT" ADD CONSTRAINT "LOGMENT_PK" PRIMARY KEY ("NOM_LOG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YOMNA"."LOGMENT" MODIFY ("IN_OUT" NOT NULL ENABLE);
  ALTER TABLE "YOMNA"."LOGMENT" MODIFY ("TYPE_L" NOT NULL ENABLE);
  ALTER TABLE "YOMNA"."LOGMENT" MODIFY ("DISPONIBILITE" NOT NULL ENABLE);
  ALTER TABLE "YOMNA"."LOGMENT" MODIFY ("NBR_CH" NOT NULL ENABLE);
  ALTER TABLE "YOMNA"."LOGMENT" MODIFY ("ADRESSE_L" NOT NULL ENABLE);
  ALTER TABLE "YOMNA"."LOGMENT" MODIFY ("NBR_ETOILE" NOT NULL ENABLE);
  ALTER TABLE "YOMNA"."LOGMENT" MODIFY ("NOM_LOG" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MAINTENIR
--------------------------------------------------------

  ALTER TABLE "YOMNA"."MAINTENIR" MODIFY ("IDTERRAIN" NOT NULL ENABLE);
  ALTER TABLE "YOMNA"."MAINTENIR" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARTICIPANT
--------------------------------------------------------

  ALTER TABLE "YOMNA"."PARTICIPANT" MODIFY ("MEDAILLE" NOT NULL ENABLE);
  ALTER TABLE "YOMNA"."PARTICIPANT" MODIFY ("NATIONALITE" NOT NULL ENABLE);
  ALTER TABLE "YOMNA"."PARTICIPANT" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "YOMNA"."PARTICIPANT" MODIFY ("ETAT" NOT NULL ENABLE);
  ALTER TABLE "YOMNA"."PARTICIPANT" MODIFY ("EQUIPE" NOT NULL ENABLE);
  ALTER TABLE "YOMNA"."PARTICIPANT" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "YOMNA"."PARTICIPANT" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "YOMNA"."PARTICIPANT" ADD CONSTRAINT "PARTICIPANT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YOMNA"."PARTICIPANT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSONNEL
--------------------------------------------------------

  ALTER TABLE "YOMNA"."PERSONNEL" ADD CONSTRAINT "PERSONNEL_PK" PRIMARY KEY ("CIN_P")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YOMNA"."PERSONNEL" MODIFY ("ADRESS_P" NOT NULL ENABLE);
  ALTER TABLE "YOMNA"."PERSONNEL" MODIFY ("NUM_TEL_P" NOT NULL ENABLE);
  ALTER TABLE "YOMNA"."PERSONNEL" MODIFY ("DATE_N_P" NOT NULL ENABLE);
  ALTER TABLE "YOMNA"."PERSONNEL" MODIFY ("GRADE_P" NOT NULL ENABLE);
  ALTER TABLE "YOMNA"."PERSONNEL" MODIFY ("CIN_P" NOT NULL ENABLE);
  ALTER TABLE "YOMNA"."PERSONNEL" MODIFY ("PRENOM_P" NOT NULL ENABLE);
  ALTER TABLE "YOMNA"."PERSONNEL" MODIFY ("NOM_P" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SPECTATEUR
--------------------------------------------------------

  ALTER TABLE "YOMNA"."SPECTATEUR" MODIFY ("ID_TER" NOT NULL ENABLE);
  ALTER TABLE "YOMNA"."SPECTATEUR" ADD CONSTRAINT "SPECTATEUR_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YOMNA"."SPECTATEUR" MODIFY ("NUM_SIEGE" NOT NULL ENABLE);
  ALTER TABLE "YOMNA"."SPECTATEUR" MODIFY ("AGE" NOT NULL ENABLE);
  ALTER TABLE "YOMNA"."SPECTATEUR" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "YOMNA"."SPECTATEUR" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SPORT
--------------------------------------------------------

  ALTER TABLE "YOMNA"."SPORT" MODIFY ("ID_PA" NOT NULL ENABLE);
  ALTER TABLE "YOMNA"."SPORT" ADD CONSTRAINT "SPORT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YOMNA"."SPORT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "YOMNA"."SPORT" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "YOMNA"."SPORT" MODIFY ("NOM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TERRAIN
--------------------------------------------------------

  ALTER TABLE "YOMNA"."TERRAIN" MODIFY ("ID_PAR" NOT NULL ENABLE);
  ALTER TABLE "YOMNA"."TERRAIN" ADD CONSTRAINT "TERRAIN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YOMNA"."TERRAIN" MODIFY ("NOM_T" NOT NULL ENABLE);
  ALTER TABLE "YOMNA"."TERRAIN" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table LOGMENT
--------------------------------------------------------

  ALTER TABLE "YOMNA"."LOGMENT" ADD CONSTRAINT "LOGMENT_FK1" FOREIGN KEY ("ID_PAR")
	  REFERENCES "YOMNA"."PARTICIPANT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MAINTENIR
--------------------------------------------------------

  ALTER TABLE "YOMNA"."MAINTENIR" ADD CONSTRAINT "PK7" FOREIGN KEY ("IDTERRAIN")
	  REFERENCES "YOMNA"."TERRAIN" ("ID") ENABLE;
  ALTER TABLE "YOMNA"."MAINTENIR" ADD CONSTRAINT "PK8" FOREIGN KEY ("CIN")
	  REFERENCES "YOMNA"."PERSONNEL" ("CIN_P") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SPECTATEUR
--------------------------------------------------------

  ALTER TABLE "YOMNA"."SPECTATEUR" ADD CONSTRAINT "FK" FOREIGN KEY ("ID_TER")
	  REFERENCES "YOMNA"."TERRAIN" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SPORT
--------------------------------------------------------

  ALTER TABLE "YOMNA"."SPORT" ADD CONSTRAINT "PK4" FOREIGN KEY ("ID_PA")
	  REFERENCES "YOMNA"."PARTICIPANT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TERRAIN
--------------------------------------------------------

  ALTER TABLE "YOMNA"."TERRAIN" ADD CONSTRAINT "PKPAR" FOREIGN KEY ("ID_PAR")
	  REFERENCES "YOMNA"."PARTICIPANT" ("ID") ENABLE;
