--------------------------------------------------------
--  Fichier créé - jeudi-novembre-04-2021   
--------------------------------------------------------
DROP TABLE "AMINE"."LOGMENT" cascade constraints;
DROP TABLE "AMINE"."MAINTENIR" cascade constraints;
DROP TABLE "AMINE"."PARTICIPANT" cascade constraints;
DROP TABLE "AMINE"."PERSONNEL" cascade constraints;
DROP TABLE "AMINE"."SPECTATEUR" cascade constraints;
DROP TABLE "AMINE"."SPORT" cascade constraints;
DROP TABLE "AMINE"."TERRAIN" cascade constraints;
--------------------------------------------------------
--  DDL for Table LOGMENT
--------------------------------------------------------

  CREATE TABLE "AMINE"."LOGMENT" 
   (	"NOM_LOG" VARCHAR2(20 BYTE), 
	"NBR_ETOILE" NUMBER, 
	"ADRESSE_L" VARCHAR2(20 BYTE), 
	"NBR_CH" NUMBER, 
	"DISPONIBILITE" VARCHAR2(20 BYTE), 
	"TYPE_L" VARCHAR2(20 BYTE), 
	"IN_OUT" VARCHAR2(20 BYTE), 
	"ID_PAR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MAINTENIR
--------------------------------------------------------

  CREATE TABLE "AMINE"."MAINTENIR" 
   (	"CIN" NUMBER, 
	"IDTERRAIN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PARTICIPANT
--------------------------------------------------------

  CREATE TABLE "AMINE"."PARTICIPANT" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"EQUIPE" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"NATIONALITE" VARCHAR2(20 BYTE), 
	"DATE_NAIS" DATE, 
	"MEDAILLE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERSONNEL
--------------------------------------------------------

  CREATE TABLE "AMINE"."PERSONNEL" 
   (	"NOM_P" VARCHAR2(20 BYTE), 
	"PRENOM_P" VARCHAR2(20 BYTE), 
	"CIN_P" NUMBER, 
	"GRADE_P" VARCHAR2(20 BYTE), 
	"DATE_N_P" DATE, 
	"NUM_TEL_P" NUMBER, 
	"ADRESS_P" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SPECTATEUR
--------------------------------------------------------

  CREATE TABLE "AMINE"."SPECTATEUR" 
   (	"CIN" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"AGE" NUMBER, 
	"NUM_SIEGE" NUMBER, 
	"ID_TER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SPORT
--------------------------------------------------------

  CREATE TABLE "AMINE"."SPORT" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"NBR_PARTICIPANT" VARCHAR2(20 BYTE), 
	"DUREE_MATCH" NUMBER, 
	"ID_PA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TERRAIN
--------------------------------------------------------

  CREATE TABLE "AMINE"."TERRAIN" 
   (	"ID" NUMBER, 
	"NOM_T" VARCHAR2(20 BYTE), 
	"TYPE_T" VARCHAR2(20 BYTE), 
	"ETAT_T" VARCHAR2(20 BYTE), 
	"CAPACITE" VARCHAR2(20 BYTE), 
	"ID_PAR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into AMINE.LOGMENT
SET DEFINE OFF;
REM INSERTING into AMINE.MAINTENIR
SET DEFINE OFF;
REM INSERTING into AMINE.PARTICIPANT
SET DEFINE OFF;
Insert into AMINE.PARTICIPANT (ID,NOM,PRENOM,EQUIPE,ETAT,TYPE,NATIONALITE,DATE_NAIS,MEDAILLE) values ('264185','nouira','amine','brazil','bless??','foot','suisse',to_date('31/10/21','DD/MM/RR'),'16');
Insert into AMINE.PARTICIPANT (ID,NOM,PRENOM,EQUIPE,ETAT,TYPE,NATIONALITE,DATE_NAIS,MEDAILLE) values ('0','amine','samir','brazil','bless??','foot','aqsd',null,'3');
Insert into AMINE.PARTICIPANT (ID,NOM,PRENOM,EQUIPE,ETAT,TYPE,NATIONALITE,DATE_NAIS,MEDAILLE) values ('5624','ddfsqd','fdqsqfds','brazil','bless??','foot','dsff',null,'20');
Insert into AMINE.PARTICIPANT (ID,NOM,PRENOM,EQUIPE,ETAT,TYPE,NATIONALITE,DATE_NAIS,MEDAILLE) values ('2356','nouira','amine','brazil','bless??','foot','germany',to_date('01/01/00','DD/MM/RR'),'13');
Insert into AMINE.PARTICIPANT (ID,NOM,PRENOM,EQUIPE,ETAT,TYPE,NATIONALITE,DATE_NAIS,MEDAILLE) values ('5065','nouira','amine','brazil','bless??','foot','tunisian',to_date('30/11/05','DD/MM/RR'),'30');
Insert into AMINE.PARTICIPANT (ID,NOM,PRENOM,EQUIPE,ETAT,TYPE,NATIONALITE,DATE_NAIS,MEDAILLE) values ('31562','nouira','amine','brazil','bless??','foot','tunisia',to_date('01/01/00','DD/MM/RR'),'999946');
Insert into AMINE.PARTICIPANT (ID,NOM,PRENOM,EQUIPE,ETAT,TYPE,NATIONALITE,DATE_NAIS,MEDAILLE) values ('859452','tekaya','syrine','germany','Bonne','basket','tunisia',to_date('13/01/01','DD/MM/RR'),'3');
Insert into AMINE.PARTICIPANT (ID,NOM,PRENOM,EQUIPE,ETAT,TYPE,NATIONALITE,DATE_NAIS,MEDAILLE) values ('55456','nouira','dzqsd','brazil','bless??','foot','sdqs',to_date('01/01/00','DD/MM/RR'),'62323');
Insert into AMINE.PARTICIPANT (ID,NOM,PRENOM,EQUIPE,ETAT,TYPE,NATIONALITE,DATE_NAIS,MEDAILLE) values ('2315','dsqf','nouira','brazil','bless??','foot','tunisie',to_date('01/01/00','DD/MM/RR'),'0');
Insert into AMINE.PARTICIPANT (ID,NOM,PRENOM,EQUIPE,ETAT,TYPE,NATIONALITE,DATE_NAIS,MEDAILLE) values ('564548','layouni','yomna','germany','Bonne','basket','germany',to_date('28/09/01','DD/MM/RR'),'1');
REM INSERTING into AMINE.PERSONNEL
SET DEFINE OFF;
REM INSERTING into AMINE.SPECTATEUR
SET DEFINE OFF;
REM INSERTING into AMINE.SPORT
SET DEFINE OFF;
REM INSERTING into AMINE.TERRAIN
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index LOGMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AMINE"."LOGMENT_PK" ON "AMINE"."LOGMENT" ("NOM_LOG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PARTICIPANT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AMINE"."PARTICIPANT_PK" ON "AMINE"."PARTICIPANT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PERSONNEL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AMINE"."PERSONNEL_PK" ON "AMINE"."PERSONNEL" ("CIN_P") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SPECTATEUR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AMINE"."SPECTATEUR_PK" ON "AMINE"."SPECTATEUR" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SPORT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AMINE"."SPORT_PK" ON "AMINE"."SPORT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TERRAIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AMINE"."TERRAIN_PK" ON "AMINE"."TERRAIN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table LOGMENT
--------------------------------------------------------

  ALTER TABLE "AMINE"."LOGMENT" MODIFY ("ID_PAR" NOT NULL ENABLE);
  ALTER TABLE "AMINE"."LOGMENT" ADD CONSTRAINT "LOGMENT_PK" PRIMARY KEY ("NOM_LOG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AMINE"."LOGMENT" MODIFY ("IN_OUT" NOT NULL ENABLE);
  ALTER TABLE "AMINE"."LOGMENT" MODIFY ("TYPE_L" NOT NULL ENABLE);
  ALTER TABLE "AMINE"."LOGMENT" MODIFY ("DISPONIBILITE" NOT NULL ENABLE);
  ALTER TABLE "AMINE"."LOGMENT" MODIFY ("NBR_CH" NOT NULL ENABLE);
  ALTER TABLE "AMINE"."LOGMENT" MODIFY ("ADRESSE_L" NOT NULL ENABLE);
  ALTER TABLE "AMINE"."LOGMENT" MODIFY ("NBR_ETOILE" NOT NULL ENABLE);
  ALTER TABLE "AMINE"."LOGMENT" MODIFY ("NOM_LOG" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MAINTENIR
--------------------------------------------------------

  ALTER TABLE "AMINE"."MAINTENIR" MODIFY ("IDTERRAIN" NOT NULL ENABLE);
  ALTER TABLE "AMINE"."MAINTENIR" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARTICIPANT
--------------------------------------------------------

  ALTER TABLE "AMINE"."PARTICIPANT" MODIFY ("MEDAILLE" NOT NULL ENABLE);
  ALTER TABLE "AMINE"."PARTICIPANT" MODIFY ("NATIONALITE" NOT NULL ENABLE);
  ALTER TABLE "AMINE"."PARTICIPANT" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "AMINE"."PARTICIPANT" MODIFY ("ETAT" NOT NULL ENABLE);
  ALTER TABLE "AMINE"."PARTICIPANT" MODIFY ("EQUIPE" NOT NULL ENABLE);
  ALTER TABLE "AMINE"."PARTICIPANT" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "AMINE"."PARTICIPANT" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "AMINE"."PARTICIPANT" ADD CONSTRAINT "PARTICIPANT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AMINE"."PARTICIPANT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSONNEL
--------------------------------------------------------

  ALTER TABLE "AMINE"."PERSONNEL" ADD CONSTRAINT "PERSONNEL_PK" PRIMARY KEY ("CIN_P")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AMINE"."PERSONNEL" MODIFY ("ADRESS_P" NOT NULL ENABLE);
  ALTER TABLE "AMINE"."PERSONNEL" MODIFY ("NUM_TEL_P" NOT NULL ENABLE);
  ALTER TABLE "AMINE"."PERSONNEL" MODIFY ("DATE_N_P" NOT NULL ENABLE);
  ALTER TABLE "AMINE"."PERSONNEL" MODIFY ("GRADE_P" NOT NULL ENABLE);
  ALTER TABLE "AMINE"."PERSONNEL" MODIFY ("CIN_P" NOT NULL ENABLE);
  ALTER TABLE "AMINE"."PERSONNEL" MODIFY ("PRENOM_P" NOT NULL ENABLE);
  ALTER TABLE "AMINE"."PERSONNEL" MODIFY ("NOM_P" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SPECTATEUR
--------------------------------------------------------

  ALTER TABLE "AMINE"."SPECTATEUR" MODIFY ("ID_TER" NOT NULL ENABLE);
  ALTER TABLE "AMINE"."SPECTATEUR" ADD CONSTRAINT "SPECTATEUR_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AMINE"."SPECTATEUR" MODIFY ("NUM_SIEGE" NOT NULL ENABLE);
  ALTER TABLE "AMINE"."SPECTATEUR" MODIFY ("AGE" NOT NULL ENABLE);
  ALTER TABLE "AMINE"."SPECTATEUR" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "AMINE"."SPECTATEUR" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SPORT
--------------------------------------------------------

  ALTER TABLE "AMINE"."SPORT" MODIFY ("ID_PA" NOT NULL ENABLE);
  ALTER TABLE "AMINE"."SPORT" ADD CONSTRAINT "SPORT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AMINE"."SPORT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "AMINE"."SPORT" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "AMINE"."SPORT" MODIFY ("NOM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TERRAIN
--------------------------------------------------------

  ALTER TABLE "AMINE"."TERRAIN" MODIFY ("ID_PAR" NOT NULL ENABLE);
  ALTER TABLE "AMINE"."TERRAIN" ADD CONSTRAINT "TERRAIN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AMINE"."TERRAIN" MODIFY ("NOM_T" NOT NULL ENABLE);
  ALTER TABLE "AMINE"."TERRAIN" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table LOGMENT
--------------------------------------------------------

  ALTER TABLE "AMINE"."LOGMENT" ADD CONSTRAINT "LOGMENT_FK1" FOREIGN KEY ("ID_PAR")
	  REFERENCES "AMINE"."PARTICIPANT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MAINTENIR
--------------------------------------------------------

  ALTER TABLE "AMINE"."MAINTENIR" ADD CONSTRAINT "PK7" FOREIGN KEY ("IDTERRAIN")
	  REFERENCES "AMINE"."TERRAIN" ("ID") ENABLE;
  ALTER TABLE "AMINE"."MAINTENIR" ADD CONSTRAINT "PK8" FOREIGN KEY ("CIN")
	  REFERENCES "AMINE"."PERSONNEL" ("CIN_P") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SPECTATEUR
--------------------------------------------------------

  ALTER TABLE "AMINE"."SPECTATEUR" ADD CONSTRAINT "FK" FOREIGN KEY ("ID_TER")
	  REFERENCES "AMINE"."TERRAIN" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SPORT
--------------------------------------------------------

  ALTER TABLE "AMINE"."SPORT" ADD CONSTRAINT "PK4" FOREIGN KEY ("ID_PA")
	  REFERENCES "AMINE"."PARTICIPANT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TERRAIN
--------------------------------------------------------

  ALTER TABLE "AMINE"."TERRAIN" ADD CONSTRAINT "PKPAR" FOREIGN KEY ("ID_PAR")
	  REFERENCES "AMINE"."PARTICIPANT" ("ID") ENABLE;
